passwd:
  users:
    - name: jeffl
      password_hash: "$1$linux$Jkofsu0Cak8oAy8lOAOPB0"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRcJWlhZTxUNxYVGvVhqkTD2+NyIi6wASdoqm+jfQkF2lnxKROVpODCZ9Yw7J6/V0dQZDc58vAm+tExySB4qkXpvTR0pUrtDZDu0ZiX9E1ErsW14JZKsUCJbJ9z5L41eI13k637vD+o3QGCM7OkdDc0wn8w089EPEcTVXjLhKEtzU6dwkas59mklQNzL4CfaoIFG7nqzuh12nCsXMmrSoP50Crywor4Xu9vgkNse60NENO4uwsrlvEL5sOPGOe1vbEaX8DTkjjA6SVoxKklzSQApZLzQR76ZnQPrAP8ut9qCavJcEV5r14GOBrL1qm0Wz9fBaf3aTBXzI5LZMTT3fz Jeff@Jeffs-MacBook-Air.local
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKfDqH0x7z1svr33vlssCQFkROhBB//7F4gN10JFut4vSFnEGEaDG+L4kMpE6dPuF1hTIaZ7TIawVjjRm8VRCC4pAyYHwgVoIee+YgC08owobRz8iC9gkkxA1jRQpAe/ZSYkfpa22XUCzJOu1sRJXbennlosw1ttdT8OH8dznaRVe5I69mpx3VVdh1Xqza2QLZPLvYlwoCzWdIs4zyS2W/ZGDDzxq46LEv3FfJW/hTn/FjCoHe+lrZPkK+WAfSqy3t9aVhtrHNWhdFpn4X5DwpRQDtJCCDN/qXw6rYCCH3xrrKb5r7W3jLFCstAZIBuWPZzuJeLCdr80YvTdB0j+XF jeffl@jumper-taiping
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvDO/arcVktT4WgJDhbP0cMu1CSNW0y1svMw/JcnLOBZ0puloIjF7E7PUSkRQVqfAUG34G9h0szhvcGpmquim0UJQFZKFhcuKjbgNWgKje/svB2UKqlxx5TtpdULo8dCYWwDK6rHmMU1CEZFWIeZiwnjVmWUyzndunfmBe3sFZ/vWSz2Ab0GslMxqQp8wpqCXezBH3AKo2FKb4Qj1vQxcp1bPKC1gBj/pa1ih/iOPp2yHnMhzq+t/S//bNUAJ+GgpJrXJL+xh8EKtGQ8qOGJ8xiWirEBJL6PFS8eY7Tv9j67PSbtGfPX54xXuUu/nvY9JmaIhfOq1Jvwex3wGVIpnl jeffl@JeffWorkShop
      create:
        home_dir: /home/jeffl
        groups:
          - docker
          - sudo
        shell: /bin/bash

    - name: core
      password_hash: "$1$linux$Jkofsu0Cak8oAy8lOAOPB0"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRcJWlhZTxUNxYVGvVhqkTD2+NyIi6wASdoqm+jfQkF2lnxKROVpODCZ9Yw7J6/V0dQZDc58vAm+tExySB4qkXpvTR0pUrtDZDu0ZiX9E1ErsW14JZKsUCJbJ9z5L41eI13k637vD+o3QGCM7OkdDc0wn8w089EPEcTVXjLhKEtzU6dwkas59mklQNzL4CfaoIFG7nqzuh12nCsXMmrSoP50Crywor4Xu9vgkNse60NENO4uwsrlvEL5sOPGOe1vbEaX8DTkjjA6SVoxKklzSQApZLzQR76ZnQPrAP8ut9qCavJcEV5r14GOBrL1qm0Wz9fBaf3aTBXzI5LZMTT3fz Jeff@Jeffs-MacBook-Air.local
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKfDqH0x7z1svr33vlssCQFkROhBB//7F4gN10JFut4vSFnEGEaDG+L4kMpE6dPuF1hTIaZ7TIawVjjRm8VRCC4pAyYHwgVoIee+YgC08owobRz8iC9gkkxA1jRQpAe/ZSYkfpa22XUCzJOu1sRJXbennlosw1ttdT8OH8dznaRVe5I69mpx3VVdh1Xqza2QLZPLvYlwoCzWdIs4zyS2W/ZGDDzxq46LEv3FfJW/hTn/FjCoHe+lrZPkK+WAfSqy3t9aVhtrHNWhdFpn4X5DwpRQDtJCCDN/qXw6rYCCH3xrrKb5r7W3jLFCstAZIBuWPZzuJeLCdr80YvTdB0j+XF jeffl@jumper-taiping
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvDO/arcVktT4WgJDhbP0cMu1CSNW0y1svMw/JcnLOBZ0puloIjF7E7PUSkRQVqfAUG34G9h0szhvcGpmquim0UJQFZKFhcuKjbgNWgKje/svB2UKqlxx5TtpdULo8dCYWwDK6rHmMU1CEZFWIeZiwnjVmWUyzndunfmBe3sFZ/vWSz2Ab0GslMxqQp8wpqCXezBH3AKo2FKb4Qj1vQxcp1bPKC1gBj/pa1ih/iOPp2yHnMhzq+t/S//bNUAJ+GgpJrXJL+xh8EKtGQ8qOGJ8xiWirEBJL6PFS8eY7Tv9j67PSbtGfPX54xXuUu/nvY9JmaIhfOq1Jvwex3wGVIpnl jeffl@JeffWorkShop


storage:
  filesystems:
    - name: filesystem1
      mount:
        device: /dev/disk/by-partlabel/ROOT
        format: btrfs
        create:
          force: true
          options:
            - -L
            - ROOT
